version: '3.9'

services:

  backend:
    image: palkkatieto-back
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
    
  frontend:
    image: palkkatieto-front
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend


