name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build_backend: 
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Install Poetry
              run: |
                cd backend
                pip install poetry

            - name:  Install dependencies
              run: |
                cd backend
                poetry install

            - name: Run Pylint
              run: |
                cd backend
                poetry run pylint src
    
            - name: Run Pytest
              run: |
                cd backend
                poetry run pytest src/tests
              env:
                  DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
                  SECRET_KEY: SECRET
    
    build_frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20.11.0
            
            - name: Install Node
              run: |
                cd frontend
                npm ci

            - name: Run Pylint
              run: |
                cd frontend
                npm run lint --exit-zero .

    build_for_robot_tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name: Install Poetry
              run: |
                cd backend
                pip install poetry

            - name:  Install dependencies
              run: |
                cd backend
                poetry install

            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20.11.0

            - name: Install Node
              run: |
                cd frontend
                npm ci

            - name: Setup chromedriver
              uses: nanasess/setup-chromedriver@master

            - name: Configure chromedriver
              run: |
                export DISPLAY=:99
                chromedriver --url-base=/wd/hub &
                sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

            - name: Run robot tests
              run: |
                cd backend
                poetry shell
                poetry run invoke robottests
              env:
                  DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
                  SECRET_KEY: SECRET
